# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qmlsettings

# >> macros
# << macros

Summary:    Settings application made with QML
Version:    0.0.0
Release:    1
Group:      Applications/System
License:    BSD
URL:        https://github.com/nemomobile/qmlsettings/
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlsettings.yaml
Requires:   qt-components-qt5
Requires:   nemo-qml-plugin-time-qt5
Requires:   nemo-qml-plugin-accounts-qt5
Requires:   nemo-qml-plugin-systemsettings
Requires:   nemo-qml-plugin-signon-qt5
Requires:   telepathy-accounts-signon >= 0.0.7
Requires:   connman-qt5-declarative
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
Provides:   accounts-ui > 0.0.2
Provides:   meegotouch-controlpanel > 0.14.7.1
Provides:   meegotouch-controlpanel-l10n-engineering-english > 0.14.7.1
Provides:   meegotouchcp-about > 0.21.14
Provides:   meegotouchcp-bluetooth > 0.0.9
Provides:   meegotouchcp-bluetooth-libmeegobluetooth > 0.0.9
Provides:   meegotouchcp-cellular > 0.0.1
Provides:   meegotouchcp-connman > 0.2.5
Provides:   meegotouchcp-datetime > 0.10.8
Provides:   meegotouchcp-display > 0.21.14
Provides:   meegotouchcp-gprs > 0.21.14
Provides:   meegotouchcp-language > 0.11.3
Provides:   meegotouchcp-offline > 0.21.14
Provides:   meegotouchcp-privatemodeapplet > 1.5.8
Provides:   meegotouchcp-regionformat > 0.5.3
Provides:   meegotouchcp-reset > 0.21.14
Provides:   meegotouchcp-skeleton > 0.14.7
Provides:   meegotouchcp-sound > 0.21.14
Provides:   meegotouchcp-test > 0.21.14
Provides:   meegotouchcp-theme > 0.21.14
Provides:   meegotouchcp-usb > 0.21.14
Provides:   meegotouchcp-wallpaper > 0.21.14
Provides:   meegotouchcp-warranty > 0.21.14
Provides:   meegotouchcp-regionformat-l10n-engineering-english > 0.5.3
Provides:   meegotouchcp-language-l10n-engineering-english > 0.11.3
Provides:   meegotouchcp-datetime-l10n-engineering-english > 0.10.8
Provides:   nemo-control-panel-applet-power > 0.1.2
Provides:   libmeegocontrolpanel > 0.14.7.1
Provides:   meegotouch-controlpanelapplets > 0.21.14
Provides:   meegotouchcp-battery > 0.21.13
Obsoletes:   accounts-ui <= 0.0.2
Obsoletes:   meegotouch-controlpanel <= 0.14.7.1
Obsoletes:   meegotouch-controlpanel-l10n-engineering-english <= 0.14.7.1
Obsoletes:   meegotouchcp-about <= 0.21.14
Obsoletes:   meegotouchcp-bluetooth <= 0.0.9
Obsoletes:   meegotouchcp-bluetooth-libmeegobluetooth <= 0.0.9
Obsoletes:   meegotouchcp-cellular <= 0.0.1
Obsoletes:   meegotouchcp-connman <= 0.2.5
Obsoletes:   meegotouchcp-datetime <= 0.10.8
Obsoletes:   meegotouchcp-display <= 0.21.14
Obsoletes:   meegotouchcp-gprs <= 0.21.14
Obsoletes:   meegotouchcp-language <= 0.11.3
Obsoletes:   meegotouchcp-offline <= 0.21.14
Obsoletes:   meegotouchcp-privatemodeapplet <= 1.5.8
Obsoletes:   meegotouchcp-regionformat <= 0.5.3
Obsoletes:   meegotouchcp-reset <= 0.21.14
Obsoletes:   meegotouchcp-skeleton <= 0.14.7
Obsoletes:   meegotouchcp-sound <= 0.21.14
Obsoletes:   meegotouchcp-test <= 0.21.14
Obsoletes:   meegotouchcp-theme <= 0.21.14
Obsoletes:   meegotouchcp-usb <= 0.21.14
Obsoletes:   meegotouchcp-wallpaper <= 0.21.14
Obsoletes:   meegotouchcp-warranty <= 0.21.14
Obsoletes:   meegotouchcp-regionformat-l10n-engineering-english <= 0.5.3
Obsoletes:   meegotouchcp-language-l10n-engineering-english <= 0.11.3
Obsoletes:   meegotouchcp-datetime-l10n-engineering-english <= 0.10.8
Obsoletes:   nemo-control-panel-applet-power <= 0.1.2
Obsoletes:   libmeegocontrolpanel <= 0.14.7.1
Obsoletes:   meegotouch-controlpanelapplets <= 0.21.14
Obsoletes:   meegotouchcp-battery <= 0.21.13

%description
Settings application written using QML.

%package account-plugin-email
Summary:    Generic email account plugin for email
Group:      Applications/System
Requires:   %{name} = %{version}-%{release}

%description account-plugin-email
%{summary}.

%package account-plugin-jabber
Summary:    Jabber account plugin
Group:      Applications/System
Requires:   %{name} = %{version}-%{release}

%description account-plugin-jabber
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
# >> files
# << files

%files account-plugin-email
%defattr(-,root,root,-)
%{_datadir}/accounts/ui/GenericProvider.qml
# >> files account-plugin-email
# << files account-plugin-email

%files account-plugin-jabber
%defattr(-,root,root,-)
%{_datadir}/accounts/providers/jabber.provider
%{_datadir}/accounts/services/jabber.service
%{_datadir}/accounts/ui/jabber.qml
# >> files account-plugin-jabber
# << files account-plugin-jabber
