# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       qmlsettings

# >> macros
# << macros

Summary:    Settings application made with QML
Version:    0.0.0
Release:    1
Group:      Applications/System
License:    BSD
URL:        https://github.com/nemomobile/qmlsettings/
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlsettings.yaml
Requires:   qt-components
Requires:   nemo-qml-plugins-time
Requires:   nemo-qml-plugins-accounts
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  desktop-file-utils

%description
Settings application written using QML.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
# >> files
# << files
